baseurl = "https://edavidaja.com"
title = "E. David Aja"
theme = "hugo-coder"
languagecode = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableEmoji= true

[params]
    author = "E. David Aja"
    description = "David Aja's website"
    keywords = "blog,data science,rstats"
    info = "data person."
    avatarurl = "/img/edavidaja.jpg"
    # gravatar = "edavidaja@hey.com"
    footercontent = ""
    dateformat = "January 2, 2006"
    hideCredits = false
    hideCopyright = true
    rtl = false
    colorScheme = "auto"
    custom_css = []

[[params.social]]
    name = "Bluesky"
    icon = "fa-brands fa-bluesky fa-2x"
    weight = 1
    url = "https://bsky.app/profile/edavidaja.com"
[[params.social]]
    name = "Mastodon"
    icon = "fa-brands fa-mastodon fa-2x"
    weight = 2
    url = "https://mastodon.xyz/@edavidaja.com@bsky.brid.gy"
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 3
    url = "https://github.com/edavidaja/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/edavidaja/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 5
    url = "mailto:edavidaja@hey.com"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
