baseurl = "https://edavidaja.com"
title = "E. David Aja"
theme = "hugo-coder"
languagecode = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
# disqusShortname = "edavidaja"
enableEmoji= true

[params]
    author = "E. David Aja"
    description = "David Aja's website"
    keywords = "blog,data science,rstats"
    info = "data person."
    avatarurl = "/img/edavidaja.jpg"
    # gravatar = "edavidaja@hey.com"
    footercontent = ""
    dateformat = "January 2, 2006"
    hideCredits = false
    hideCopyright = true
    rtl = false
    colorScheme = "auto"
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/edavidaja/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/peeltothepithy"
[[params.social]]
    name = "Telegram"
    icon = "fa fa-telegram fa-2x"
    weight = 2
    url = "https://telegram.me/edavidaja"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/edavidaja/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 4
    url = "edavidaja@hey.com"
[[params.social]]
    name = "keybase"
    icon = "fa fa-keybase fa-2x"
    weight = 5
    url = "https://keybase.io/edavidaja"

[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
# [[menu.main]]
#     name = "Projects"
#     weight = 3
#     url = "/projects/"
# [[menu.main]]
#     name = "Contact me"
#     weight = 5
#     url = "/contact/"
