baseurl = "https://edavidaja.com"
title = "E. David Aja"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "edavidaja"

[params]
    author = "E. David Aja"
    description = "David Aja's website"
    keywords = "blog,data science,rlang"
    info = "data person."
    avatarurl = "images/edavidaja.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = true

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/edavidaja/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/edavidaja/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/edavidaja/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 4
    url = "mailto:e.david.aja@gmail.com"
[[params.social]]
    name = "keybase"
    icon = "fab fa-keybase"
    weight = 5
    url = "https://keybase.io/edavidaja"

# [[menu.main]]
#     name = "Blog"
#     weight = 1
#     url  = "/posts/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"
# [[menu.main]]
#     name = "Projects"
#     weight = 3
#     url = "/projects/"
# [[menu.main]]
#     name = "Contact me"
#     weight = 5
#     url = "/contact/"
